version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "CloudResumeChallenge-jclm1rt"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1cp596rioz4bz"
s3_prefix = "CloudResumeChallenge-jclm1rt"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
